In [2]:
import torch 
import torchvision 
import torch.nn as nn 
import torchvision.transforms as transforms
import numpy as np 

### Tensors 
Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.

Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other specialized hardware to accelerate computing

In [12]:
# Tensor Initialization 

In [16]:
# Directly from data
x = [[1,2],[3,4]]
x_tensor = torch.tensor(x)
print(x_tensor)

tensor([[1, 2],
        [3, 4]])


In [18]:
# From np array 
x_array = np.array(x) 
x_array_tensor = torch.tensor(x_array)
print(x_array_tensor)

tensor([[1, 2],
        [3, 4]])


In [23]:
# from another tensor 
x_ones = torch.ones_like(x_tensor) 
print(x_ones)

x_rand = torch.rand_like(x_tensor, dtype=torch.float) # overrides the datatype of x
print(x_rand)

x_zeroes = torch.zeros_like(x_tensor)
print(x_zeroes)

tensor([[1, 1],
        [1, 1]])
tensor([[0.9927, 0.5748],
        [0.4725, 0.1033]])
tensor([[0, 0],
        [0, 0]])


In [29]:
# with random or constant value 
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.6506, 0.6047, 0.0489],
        [0.2113, 0.1906, 0.3175]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In Python, adding a trailing comma after the last item in a tuple is a matter of style and doesn't affect the functionality. However, in certain contexts, it can improve code readability and make it easier to maintain, especially when modifying the tuple by adding or removing elements.

The version with the trailing comma `(2, 3,)` can be considered a good practice in some coding styles or guidelines because it makes it clear that the tuple has more than one element, even if there's only one element present. This can prevent errors when adding more elements to the tuple in the future, as you won't need to remember to add a comma after the last element.

In summary, while it's not strictly necessary, adding a trailing comma after the last item in a tuple can be considered a good practice for consistency and readability in Python code. However, whether or not to use it ultimately depends on the coding style guide you or your team follows.

## Tensor Attributes 

In [32]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Basic autograds 

Gradients are quite important for the optimization purpose. PyTorch provides package which can do all the computation task.

In [3]:
x = torch.randn(3)
print(x)

tensor([ 1.2541,  2.1801, -1.8786])


In [6]:
x = torch.randn(3, requires_grad = True) # by default requires_grad = false 
print(x)

tensor([ 0.3224, -0.5739, -0.6564], requires_grad=True)


In [8]:
y = x + 2 # will create the computational graph for us 
print(y)

tensor([2.3224, 1.4261, 1.3436], grad_fn=<AddBackward0>)


Here, AddBackward can be seen as we have done the backpropagation. 

In [9]:
z = y*y*2 
print(z)

tensor([10.7874,  4.0678,  3.6103], grad_fn=<MulBackward0>)


Here, MulBackward can be seen as we are doing multiplication operation. 

In [10]:
z = z.mean()
print(z) 

tensor(6.1552, grad_fn=<MeanBackward0>)


In [11]:
# to calculate the gradient 
z.backward() # dz/dx
print(x.grad) # x will store the gradient value 

tensor([3.0966, 1.9015, 1.7914])


In [44]:
# grad can only be implicitly created only for scalar outputs
x = torch.randn(3, requires_grad = True ) 
y = x + 2 

z = y*y*2 
# z.mean()
print(z) # z is not a scalar value 

tensor([6.1761, 3.6343, 1.1194], grad_fn=<MulBackward0>)


In [45]:
# to calculate gradient 
z.backward()
print(x.grad)

RuntimeError: grad can be implicitly created only for scalar outputs

In [46]:
# solution is multipying it with an vector 
v = torch.tensor([0.1, 1.0, 0.001], dtype = torch.float32)
z.backward(v)
print(x.grad)

tensor([7.0291e-01, 5.3921e+00, 2.9926e-03])


##### Preventing Gradient History
There are three ways to do this : 
1. x_requires_grad_(False)
2. x.detach()
3. with torch.no_grad():