#### What is PyTorch ? 
PyTorch is an open source machine learning and deep leaning framework. 

#### What can PyTorch be used for?
PyTorch allows you to manipulate and process data and write machine learning algorithms using Python code.

####  Why use PyTorch?
Machine learning researchers love using PyTorch. PyTorch is the most used deep learning framework on Papers With Code, a website for tracking machine learning research papers and the code repositories attached with them.

PyTorch also helps take care of many things such as GPU acceleration (making your code run faster) behind the scenes.

So you can focus on manipulating data and writing algorithms and PyTorch will make sure it runs fast.

And if companies such as Tesla and Meta (Facebook) use it to build models they deploy to power hundreds of applications, drive thousands of cars and deliver content to billions of people, it's clearly capable on the development front too.

#### Importing PyTorch 

In [2]:
import torch

# check the version 
torch.__version__

'2.3.0+cu121'

#### Introduction to Tensor 
Tensors are n-dimensional array. 

#### Creating Tensor 

In [6]:
# scalar 
# A scalar is a single number and in tensor-speak it's a zero dimension tensor.
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [7]:
scalar.ndim

0

In [8]:
# now if I want to retrieve the number from tensor 
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

In [14]:
# vector 
# A vector is a single dimension tensor but can contain many numbers.
vector = torch.tensor([1,3,4])
print(vector)

tensor([1, 3, 4])


In [15]:
vector.ndim

1

**Fun Fact**:You can tell the number of dimensions a tensor in PyTorch has by the number of square brackets on the outside ([) and you only need to count one side.

In [16]:
# check the shape of the vector 
vector.shape 

torch.Size([3])

vector has a shape of [3]. This is because of the two elements we placed inside the square brackets ([1,3,4]).

In [18]:
# Matrix 
matrix = torch.tensor([[1,2],
                       [4,5]])
matrix 

tensor([[1, 2],
        [4, 5]])

In [19]:
matrix.ndim

2

In [20]:
matrix.shape

torch.Size([2, 2])

In [21]:
# Tensor 
tensor = torch.tensor([[[1,2,3],
                        [3,3,3],
                        [6,6,6]]])
tensor 

tensor([[[1, 2, 3],
         [3, 3, 3],
         [6, 6, 6]]])

In [22]:
tensor.ndim

3

In [23]:
tensor.shape 

torch.Size([1, 3, 3])

The dimensions go outer to inner.

That means there's 1 dimension of 3 by 3.

In [24]:
tensor = torch.tensor([[1,2],
                      [3,4],
                      [6,7]])
tensor 

tensor([[1, 2],
        [3, 4],
        [6, 7]])

In [25]:
tensor.shape 

torch.Size([3, 2])

In [29]:
# random tensor 
random_tensor = torch.randn(3,4)
random_tensor , random_tensor.dtype

(tensor([[-0.4492,  0.8362, -1.6632, -0.3478],
         [ 0.9382,  0.1863,  1.2673,  0.0398],
         [-1.0447,  1.3429,  0.8029, -0.1653]]),
 torch.float32)

In [30]:
# Create a random tensor of size (224, 224, 3) = img size 
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

#### Zeros and ones 

In [34]:
zeros_tensor = torch.zeros(3,4)
zeros_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [36]:
ones_tensor = torch.ones(3,4)
ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

#### Tensor DataType 
There are many different tensor datatypes available in PyTorch.

Some are specific for CPU and some are better for GPU.

Getting to know which is which can take some time.

Generally if you see torch.cuda anywhere, the tensor is being used for GPU (since Nvidia GPUs use a computing toolkit called CUDA).

The most common type (and generally the default) is torch.float32 or torch.float.

This is referred to as "32-bit floating point".

But there's also 16-bit floating point (torch.float16 or torch.half) and 64-bit floating point (torch.float64 or torch.double).

And to confuse things even more there's also 8-bit, 16-bit, 32-bit and 64-bit integers.

In [6]:
float32_tensor = torch.tensor([3.0, 6.0 ,9.0],
                              requires_grad = False,
                              device = None,
                              dtype = None)

float32_tensor

tensor([3., 6., 9.])

In [9]:
float32_tensor.shape, float32_tensor.dtype, float32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

Aside from shape issues (tensor shapes don't match up), two of the other most common issues you'll come across in PyTorch are datatype and device issues.

For example, one of tensors is torch.float32 and the other is torch.float16 (PyTorch often likes tensors to be the same format).

Or one of your tensors is on the CPU and the other is on the GPU (PyTorch likes calculations between tensors to be on the same device).

#### Tensor Multiplication 

In [10]:
tensor = torch.tensor([1,2,3])
tensor.shape 

torch.Size([3])

In [13]:
# Element-wise matrix multiplication
tensor * tensor 

tensor([1, 4, 9])

In [14]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [15]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)